# Generated by Django 5.1.1 on 2024-09-20 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_h'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='h',
        ),
    ]
