# Generated by Django 5.1.1 on 2024-09-20 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
        ('categories', '0001_initial'),
        ('languages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name=200)),
                ('definition', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='book_photos/')),
                ('authors', models.ManyToManyField(to='authors.author')),
                ('categories', models.ManyToManyField(to='categories.category')),
                ('languages', models.ManyToManyField(to='languages.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
